[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_mfs = { path = "../lib_mfs" }
rayon = "1.6.1"
serde = "1.0.152"
serde_derive = "1.0.152"
toml = "0.5.10"
